#!/usr/bin/env bash

function get_distro() {
	if [[ -f /etc/os-release ]]
	then
		source /etc/os-release
		echo $ID
	else
		>&2 echo "Don't know how to determine distro."
		exit 1
	fi
}

WORKDIR=$(mktemp --directory)
DISTRO=$(get_distro)
ARCH=$(uname -m)

export WORKDIR
export DISTRO
export ARCH

if [ -x script/$1 ]; then
	script/$1
else
	echo "Don't know how to setup '$1'"
fi

rm -rf $WORKDIR
