- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/fdahlstrand/.dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
- name: Install stow
  become: true
  apt: 
    name: stow
