- name: Install Git
  become: true
  apt:
    name: git
- name: Set Git Username
  community.general.git_config:
    name: user.name
    scope: global
    value: "Fredrik Dahlstrand"
- name: Set Git Email
  community.general.git_config:
    name: user.email
    scope: global
    value: "32812964+fdahlstrand@users.noreply.github.com"
- name: Install GitHub CLI
  become: true
  shell: "{{ lookup('env', 'HOME') }}/.dotfiles/gh_cli.sh"

