- name: Install ripgrep
  become: true
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb
    state: present
- name: Install fd
  become: true
  apt:
    deb: https://github.com/sharkdp/fd/releases/download/v9.0.0/fd_9.0.0_amd64.deb
    state: present
- name: Clone fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ lookup('env', 'HOME') }}/repos/fzf"
- name: Install fzf
  become: true
  shell:  "{{ lookup('env', 'HOME') }}/repos/fzf/install --all --no-bash --no-fish"
- name: Install unzip
  become: true
  apt:
    name: unzip
