- name: Install zsh
  become: true
  apt:
    name: zsh
- name: Stow zsh configuration files
  shell: "stow --dir {{ lookup('env', 'HOME') }}/.dotfiles --target {{ lookup('env', 'HOME') }} zsh"
- name: Change user shell to zsh
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
- name: Install oh-my-posh
  become: true
  shell: "curl -s https://ohmyposh.dev/install.sh | bash -s -- -t {{ lookup('env', 'HOME' )}}/.cache/oh-my-posh/themes"
- name: Install zsh vi-mode
  ansible.builtin.git:
    repo: https://github.com/jeffreytse/zsh-vi-mode.git
    dest: "{{ lookup('env', 'HOME') }}/.zsh-plugins/zsh-vi-mode"
- name: Install zsh syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ lookup('env', 'HOME') }}/.zsh-plugins/zsh-syntax-highlighting"
- name: Install zsh autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ lookup('env', 'HOME') }}/.zsh-plugins/zsh-autosuggestions"
