#!/usr/bin/env bash

if ! [ -n "$NVM_DIR" ]; then
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
	source $HOME/.bashrc
fi

source $NVM_DIR/nvm.sh
nvm install --lts
nvm use --lts
npm install -g npm@latest
